### ISSUE TITLE
Error: Multiple txt Drill File (.TXT) files found in design!

### ISSUE THREAD

**Issue by koendv** [VojislavM/KiCad-Gerber-Wiki#2]
Followed your recipe. This generated two Gerber drill files, one ending in -PTH.drl for plated holes and one ending in -NPTH.drl for non-plated through holes. Renamed both to .txt and submitted the Gerbers to dirtypcbs.com. 
On the ordering page, if you click on "Layer report", this gives the following error message: Multiple txt Drill File (.TXT) files found in design!

Maybe when generating drill files select "Merge PTH and NPTH holes into one file".

**Comment by VojislavM** [comment]
Yes, you are definitely right. I will add this to the repo. Thank you for the issue.
